---
title: 'Class 6b: Data analysis of scalar implicature E5'
author: "Mike Frank"
date: "February 11, 2016"
output: 
  html_document:
    toc: true
---

Packages etc. 

```{r}
rm(list=ls())
library(tidyr)
library(dplyr)
library(rjson)
library(langcog) # devtools::install_github("langcog/langcog")
```

# Data prep

```{r}
path <- "~/Projects/Scalar Implicature/scalar_implicature/"
files <- dir(paste0(path,"production-results/e5/"), pattern = "*.json")
d.raw <- data.frame()

for (f in files) {
  jf <- paste0(path, "production-results/e5/",f)
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$WorkerId, 
                   scale = jd$answer$scale,
                   degree = jd$answer$degree,
                   stars = jd$answer$manipulation_level,
                   judgment = as.numeric(jd$answer$judgment),
                   language = jd$answer$language)
  d.raw <- bind_rows(d.raw, id)
}

# Number of participants
length(unique(d.raw$workerid))
```

Data cleanup

```{r}
d <- filter(d.raw, scale != "training1") %>%
  mutate(stars = as.numeric(as.character(stars))/20) %>%
  select(-language)

head(d)
```

# Main Analysis

Aggregation step. 

```{r}
ms <- d %>%
  mutate(stars = as.numeric(as.character(stars))/20) %>%
  group_by(scale, degree, stars) %>%
  multi_boot_standard(column = "judgment")
```

Plotting step. 

```{r}
ggplot(ms, aes(x = stars, y = mean, col = degree)) + 
  geom_line() + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  facet_wrap(~ scale)
```

