---
title: "R Notebook - simple dplyr/ggplot workflow "
output: html_notebook
---

# Preliminaries

Load the tidyverse. 

```{r}
library(tidyverse)
```

Load the data from Stiller, Goodman, & Frank (2015).

```{r}
d <- read_csv("http://langcog.stanford.edu/scales_data.csv")
```

Inspect the various variables.

```{r}
unique(d$condition)
unique(d$age.group)
length(unique(d$subid))
```

# Sanity Checks

Histogram of ages.

```{r}
ggplot(d, aes(x = age)) + 
  geom_histogram(binwidth=.25)
```

Check N observations.

```{r}
d %>%
  group_by(condition, age.group) %>%
  summarise(n_observations = n()) 
```

Check N subs.

```{r}
d %>%
  distinct(subid, condition, age.group) %>%
  group_by(condition, age.group) %>%
  summarise(n_subs = n())
```

# Plots

First global plot, not that informative but better than nothing. Illustrates the power of geom_smooth.

```{r}
ggplot(d, aes(x = age, y = correct, col = condition)) + 
  geom_point() + 
  geom_smooth(method="glm") 
```

Next, use subject means.

```{r}
sub_means <- d %>%
  group_by(condition, age, subid) %>%
  summarise(correct = mean(correct))

ggplot(sub_means, 
       aes(x = age, y = correct, col = condition)) + 
  geom_point() + 
  geom_smooth()
```

And condition-by-subject means. 

```{r}
cond_means <- d %>%
  group_by(condition, age.group, subid) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = mean(correct))

ggplot(cond_means, 
       aes(x = age.group, y = correct, col = condition)) + 
  geom_point() + 
  geom_line() + 
  ylim(c(0,1)) + 
  ggthemes::theme_few() + 
  ggthemes::scale_colour_solarized() + 
  ylab("Proportion Inferences Correct") + 
  xlab("Age (Years)")
```


```{r}
ggplot(cond_means, 
       aes(x = age.group, y = correct, fill = condition)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(c(0,1)) + 
  ggthemes::theme_few() + 
  ggthemes::scale_fill_solarized() + 
  ylab("Proportion Inferences Correct") + 
  xlab("Age (Years)")
```

